[package]
name = "adventjs-2024-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["day1", "day10", "day11", "day12", "day13", "day14", "day2", "day3", "day5", "day6", "day7", "day8", "day9"]
